export const EVM_PROVIDER_STATE = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
}

export const EVM_PROVIDER_CONNECTION_ERROR = 'EVM_PROVIDER_CONNECTION_ERROR'
